[package]
name = "price-chart-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = { version = "25.0.2", features = ["webgpu", "webgl", "wgsl"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = [
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "console",
    "WebSocket",
    "MessageEvent",
    "ErrorEvent",
    "CloseEvent",
    "BinaryType",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
    "AbortController",
    "AbortSignal",
    "MouseEvent",
    "WheelEvent",
    "EventTarget",
    "AddEventListenerOptions",
    "CustomEvent",
    "Event",
    "DomRect",
    "Performance"
]}
js-sys = "0.3.77"
raw-window-handle = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-utils = "0.2"
bytemuck = { version = "1.14", features = ["derive"] }
rayon = "1.8"
