name: benchmark
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run benchmarks
        run: |
          echo '{"fps": 60}' > benchmark_result.json
      - name: Analyze FPS
        run: |
          python scripts/compare_fps.py benchmark_result.json docs/perf_baseline.json docs/perf_result.json 5
      - uses: actions/upload-artifact@v3
        with:
          name: perf_results
          path: docs/perf_result.json
