name: build
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: write-all
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install trunk
        run: cargo install trunk
      - name: Clean dist
        run: rm -rf dist
      - name: Build
        run: trunk build --release --dist dist --public-url /webgpu-candles/dev/
      - name: Save version
        run: echo ${{ github.sha }} > dist/version
      - name: Copy dist to docs/dev
        run: |
          mkdir -p docs/dev
          cp -r dist/* docs/dev/
      - name: Commit dist
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f dist docs
          git commit -m "Update dist" || echo "No changes"
          git push

