name: deploy-monitor
# docs/version contains the SHA of the last commit
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
concurrency:
  group: deploy-monitor-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  monitor:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Check version
        id: check_version
        run: |
          for i in {1..6}; do
            version=$(curl -fsSL https://qqrm.github.io/webgpu-candles/version)
            if [ "$version" = "${{ github.event.workflow_run.head_sha }}" ]; then
              echo "version=$version" >> "$GITHUB_OUTPUT"
              exit 0
            fi
            sleep 300
          done
          echo "Version not updated"
          exit 1


