name: perf
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Run benchmarks
        run: wasm-pack test --headless --chrome -- --nocapture | tee perf.log
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: perf-log
          path: perf.log
