name: perf
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: perf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install rustup if needed
        run: |
          if ! command -v rustup &>/dev/null; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-delay 5 --retry-connrefused --location --silent --show-error --fail https://sh.rustup.rs | sh -s -- --default-toolchain none -y
            echo "$CARGO_HOME/bin" >> $GITHUB_PATH
          fi
      - name: Install wasm-pack
        run: cargo install wasm-pack --version 0.13.1
      - name: Run benchmarks
        run: wasm-pack test --headless --chrome -- --nocapture | tee perf.log
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: perf-log
          path: perf.log
