name: release
on:
  release:
    types: [published]
  workflow_dispatch:

permissions: write-all
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install trunk
        run: cargo install trunk
      - name: Clean dist
        run: rm -rf dist
      - name: Build
        run: trunk build --release --no-sri --dist dist --public-url /webgpu-candles/
      - name: Save version
        run: echo ${{ github.sha }} > dist/version
      - name: Copy dist to docs
        run: |
          cp -r dist/* docs/
          mkdir -p docs/res
          cp -r res/* docs/res/
      - name: Commit release build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Update release build" || echo "No changes"
          git push
