name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install rustup if needed
        run: |
          if ! command -v rustup &>/dev/null; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-delay 5 --retry-connrefused --location --silent --show-error --fail https://sh.rustup.rs | sh -s -- --default-toolchain none -y
            echo "$CARGO_HOME/bin" >> $GITHUB_PATH
          fi
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Install wasm-tools
        run: cargo install wasm-tools
      - name: Cargo fmt check
        run: cargo fmt --all -- --check
      - name: Cargo check
        run: cargo check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests with coverage
        run: wasm-pack test --headless --chrome --coverage --log-level debug
      - name: Generate lcov
        run: wasm-tools coverage target/wasm32-unknown-unknown/debug/deps/*.wasm > lcov.info
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: lcov.info
