name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Cargo fmt
        run: cargo fmt --all
      - name: Cargo fmt check
        run: cargo fmt --all -- --check
      - name: Cargo check
        run: cargo check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: wasm-pack test --headless --chrome
