name: test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: cargo install wasm-pack --version 0.10.3
      - name: Install wasm-tools
        run: cargo install wasm-tools --version 0.2.0
      - name: Update dependencies
        run: cargo update
      - name: Cargo fmt check
        run: cargo fmt --all -- --check
      - name: Cargo check
        run: cargo check --all-targets
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings || echo 'Clippy warnings found'
      - name: Run tests with coverage
        run: wasm-pack test --headless --chrome --coverage
      - name: Generate lcov
        run: wasm-tools coverage target/wasm32-unknown-unknown/debug/deps/*.wasm > lcov.info
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: lcov.info
