name: test
on: [pull_request]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
          components: rust-src
      - name: Install rustup if needed
        run: |
          if ! command -v rustup &>/dev/null; then
            curl --proto '=https' --tlsv1.2 --retry 10 --retry-delay 5 --retry-connrefused --location --silent --show-error --fail https://sh.rustup.rs | sh -s -- --default-toolchain none -y
            echo "$CARGO_HOME/bin" >> $GITHUB_PATH
          fi
      - name: Install wasm-pack
        run: cargo install wasm-pack --version 0.13.1
      - name: Install wasm-tools
        run: cargo install wasm-tools
      - name: Update dependencies
        run: cargo update
      - name: Cargo check
        run: cargo check --all-targets
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings || echo 'Clippy warnings found'
      - name: Run tests
        run: wasm-pack test --headless --chrome
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov
      - name: Generate coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --target wasm32-unknown-unknown -Z build-std=std,panic_abort
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: lcov.info
